// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThesisDB.Models;

#nullable disable

namespace ThesisDB.Migrations
{
    [DbContext(typeof(ThesisDbContext))]
    [Migration("20260515120904_MakeStudentOptional")]
    partial class MakeStudentOptional
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("ThesisDB.Models.Programme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Programmes");
                });

            modelBuilder.Entity("ThesisDB.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContentVal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContentWt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DifficultyVal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DifficultyWt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Evaluation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Grade")
                        .HasColumnType("REAL");

                    b.Property<int>("LayoutVal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LayoutWt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LiteratureVal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LiteratureWt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NoveltyVal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NoveltyWt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RichnessVal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RichnessWt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Strengths")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StructureVal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StructureWt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StyleVal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StyleWt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ThesisId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Weaknesses")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ThesisId")
                        .IsUnique();

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("ThesisDB.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MatriculationNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("ThesisDB.Models.Supervisor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Supervisors");
                });

            modelBuilder.Entity("ThesisDB.Models.Thesis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProgrammeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SupervisorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProgrammeId");

                    b.HasIndex("StudentId");

                    b.HasIndex("SupervisorId");

                    b.ToTable("Theses");
                });

            modelBuilder.Entity("ThesisDB.Models.Review", b =>
                {
                    b.HasOne("ThesisDB.Models.Thesis", "Thesis")
                        .WithOne("Review")
                        .HasForeignKey("ThesisDB.Models.Review", "ThesisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Thesis");
                });

            modelBuilder.Entity("ThesisDB.Models.Thesis", b =>
                {
                    b.HasOne("ThesisDB.Models.Programme", "Programme")
                        .WithMany("Theses")
                        .HasForeignKey("ProgrammeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ThesisDB.Models.Student", "Student")
                        .WithMany("Theses")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ThesisDB.Models.Supervisor", "Supervisor")
                        .WithMany("Theses")
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Programme");

                    b.Navigation("Student");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("ThesisDB.Models.Programme", b =>
                {
                    b.Navigation("Theses");
                });

            modelBuilder.Entity("ThesisDB.Models.Student", b =>
                {
                    b.Navigation("Theses");
                });

            modelBuilder.Entity("ThesisDB.Models.Supervisor", b =>
                {
                    b.Navigation("Theses");
                });

            modelBuilder.Entity("ThesisDB.Models.Thesis", b =>
                {
                    b.Navigation("Review")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
